spring:
  datasource:
    url: jdbc:mysql://47.104.93.195:3306/poetry_db?characterEncoding=utf-8&useSSL=false
    username: root
    password: Rootizm5eeveJakqr12345!
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 80
  servlet:
    context-path: /poetry