spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poetry_db
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
      cache: false
      mode: LEGACYHTML5
      prefix: classpath:/templates/
#      suffix: .html

  redis:
      host: 127.0.0.1
      port: 6379
      jedis:
        pool:
          max-active: 100
          max-idle: 10
          max-wait: 100000
      timeout: 5000
      database: 0 #默认是索引为0的数据库


  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 25
#    smtpAuth: true
#    smtpStarttlsEnable: true
#    smtpSslTrust: smtp.qq.com
    # 此处 username 为邮箱名称
    username: 823581722@qq.com
    # 此处 password 为授权码
    password: eitsmlntwporbbeh
    properties:
              mail:
                smtp:
                  auth: true//这样才能通过验证
                  starttls:
                      enable: true
                      required: true

server:
  port: 8060
  servlet:
    context-path: /poetry

